### ISSUE TITLE
clientId and clienteSecret hardcoded in credential.dart

### ISSUE THREAD

**Issue by racr0x** [appsup-dart/firebase_admin#2]
Inside Credentials class there are hardcoded informations inside login method.
I don`t know if its an error or it was supposed to be there.

**Comment by rbellens** [comment]
These are the clientId and clientSecret to authenticate to firebase itself not to any particular firebase project. They are also hardcoded in for example the official firebase-admin-sdk for nodejs. 
Thanks for pointing this out though.
