### ISSUE TITLE
ServiceAccountMockCredential contains bad formatted access token

### ISSUE THREAD

**Issue by timalenustmf** [appsup-dart/firebase_admin#20]
The ServiceAccountMockCredential class contains an access token `mock-access-token` (line 38 in test.dart)
However access tokens should be in the JSON webtoken ( RFC 7519) standard format. mock-access-token does not following this formatting standard, hence it's being rejected when trying to use the ServiceAccountMockCredentials in a unit test.

**Comment by rbellens** [comment]
fixed in version 0.2.0-dev.2
