### ISSUE TITLE
Error on pub get firebase_admin 0.1.4

### ISSUE THREAD

**Issue by Heidelbergg** [appsup-dart/firebase_admin#26]
Getting this error when trying to pub get, not sure if it has something to do with the new version of flutter.

![billede](https://user-images.githubusercontent.com/42738065/150806448-0650666f-f5b5-494a-8ae5-1b0794a19fa6.png)

**Comment by rbellens** [comment]
This is a dependency issue. You can try to use `dependency_overrides` in `pubspec.yaml` to solve it or try to combine other versions of packages. Anyway, don't think this is an issue with this package. The latest (prerelease) version of `firebase_admin` supports the latest versions of all dependencies.
