### ISSUE TITLE
Outdated implementation of http

### ISSUE THREAD

**Issue by Ahmadre** [appsup-dart/firebase_admin#29]
```sh
> Task :app:compileFlutterBuildProdDebug
../../../.pub-cache/hosted/pub.dartlang.org/firebase_admin-0.1.4/lib/src/auth/auth_api_request.dart:37:61: Error: The argument type 'String' can't be assigned to the parameter type 'Uri'.
 - 'Uri' is from 'dart:core'.
    var response = await httpClient.post('$baseUrl$endpoint',
```

PR will follow

**Comment by rbellens** [comment]
please check if this still happens with the latest prerelease version [0.2.0-dev.7](https://pub.dev/packages/firebase_admin/versions/0.2.0-dev.7)

**Comment by Ahmadre** [comment]
> please check if this still happens with the latest prerelease version [0.2.0-dev.7](https://pub.dev/packages/firebase_admin/versions/0.2.0-dev.7)

Thanks :) I recognized that it's just fixed. But there was another deprecated usage which leads to build errors. But I'll close this issue for now.
