### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by schultek** [appsup-dart/firebase_admin#31]
@rbellens It seems like this package is not really maintained anymore. Are there any plans on continuing with this package in the near future? 

I can also offer my help if the problem is missing time. Please let me know how I can contribute.

**Comment by rbellens** [comment]
Sorry for the silence. The package is still maintained, but there are times where I can spend more or less time. Feel free to create pull requests. I'll try to follow up on them more quickly.
