### ISSUE TITLE
Unhandled Exception: Unsupported operation: Unsupported platform: android

### ISSUE THREAD

**Issue by ahmad684** [appsup-dart/firebase_admin#32]
No documentation available how to use in flutter mobile app. But when I tried to use it gives error 
Unhandled Exception: Unsupported operation: Unsupported platform: android

**Comment by rebaz94** [comment]
@ahmad684 you should not use firebase admin in client code like flutter application, it's only for server

**Comment by rbellens** [comment]
This package is indeed intended for server or command line applications. Not for frontend.
